#!/usr/bin/env bun
/**
 * fuzz-regression-generate-tests.ts — Generate bun:test file from regression corpus.
 *
 * Reads all entries from test/fuzz/regression/<category>/<name>/
 * and generates test/regression/generated.test.ts containing
 * bun:test cases that replay each entry against both moment2
 * and upstream moment.js.
 *
 * Run:  bun run scripts/fuzz-regression-generate-tests.ts
 * Then: bun test test/regression/generated.test.ts
 */

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const REGRESSION = resolve(ROOT, "test", "fuzz", "regression");
const OUTPUT = resolve(ROOT, "test", "regression", "generated.test.ts");

interface Meta {
  target: string;
  name: string;
  added: string;
  oracle: string;
  bugClass: string;
  relatedCommit?: string;
  failureDescription?: string;
  expected?: {
    isValid?: boolean;
    valueOf?: number;
  };
  source?: string;
}

interface Entry {
  category: string;
  name: string;
  input: string;
  meta: Meta;
}

function collectEntries(): Entry[] {
  const entries: Entry[] = [];
  const cats = readdirSync(REGRESSION);
  for (const cat of cats) {
    const catPath = resolve(REGRESSION, cat);
    if (!existsSync(catPath) || !statSync(catPath).isDirectory()) continue;
    if (cat === ".gitkeep") continue;
    const names = readdirSync(catPath);
    for (const name of names) {
      const entryPath = resolve(catPath, name);
      if (!statSync(entryPath).isDirectory()) continue;
      const metaPath = resolve(entryPath, "meta.json");
      const inputPath = resolve(entryPath, "input");
      if (!existsSync(metaPath) || !existsSync(inputPath)) continue;
      try {
        const meta = JSON.parse(readFileSync(metaPath, "utf-8")) as Meta;
        const input = readFileSync(inputPath, "utf-8");
        entries.push({ category: cat, name, input, meta });
      } catch {
        console.error(`  [ERR]  ${cat}/${name}: failed to parse`);
      }
    }
  }
  return entries;
}

function escapeJs(s: string): string {
  return JSON.stringify(s);
}

function categorizeTest(meta: Meta): "FIXED" | "KNOWN_DIFF" | "CRASH" | "REGRESSION" {
  const bc = meta.bugClass?.toLowerCase() ?? "";
  if (bc.includes("crash") || bc.includes("fixed")) return "FIXED";
  if (bc.includes("known") || bc.includes("diff")) return "KNOWN_DIFF";
  if (meta.source?.includes("crash")) return "CRASH";
  return "REGRESSION";
}

function generateTestFile(entries: Entry[]): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by scripts/fuzz-regression-generate-tests.ts");
  lines.push("// Do not edit directly. Re-run the generator to update.");
  lines.push("// Generated: " + new Date().toISOString().split("T")[0]);
  lines.push("");
  lines.push('import { test, expect } from "bun:test";');
  lines.push('import moment from "../../src/index.ts";');
  lines.push('import originalMoment from "../../moment/moment.js";');
  lines.push("");
  lines.push("originalMoment.suppressDeprecationWarnings = true;");
  lines.push("");

  // Group by category for cleaner output
  const byCategory = new Map<string, Entry[]>();
  for (const e of entries) {
    if (!byCategory.has(e.category)) byCategory.set(e.category, []);
    byCategory.get(e.category)!.push(e);
  }

  for (const [category, catEntries] of byCategory) {
    // Group by test type
    const byType = new Map<string, Entry[]>();
    for (const e of catEntries) {
      const t = categorizeTest(e.meta);
      if (!byType.has(t)) byType.set(t, []);
      byType.get(t)!.push(e);
    }

    for (const [testType, typeEntries] of byType) {
      lines.push(`// ── ${testType}: ${category} (${typeEntries.length} entries) ──`);
      lines.push("");

      const varName = `${testType}_${category}`.toUpperCase().replace(/[^A-Z0-9_]/g, "_");
      const inputs: string[] = [];
      const names: string[] = [];

      for (const e of typeEntries) {
        inputs.push(escapeJs(e.input));
        const desc = `${e.meta.bugClass}: ${e.name}`;
        names.push(escapeJs(desc.length > 80 ? desc.slice(0, 77) + "..." : desc));
      }

      // For entries that need per-input assertions, generate individual tests
      for (const e of typeEntries) {
        const input = escapeJs(e.input);
        const desc = escapeJs(`${e.meta.bugClass}: ${e.name}`);

        const hasExpectedIsValid = e.meta.expected != null &&
          Object.prototype.hasOwnProperty.call(e.meta.expected, "isValid");
        const hasExpectedValueOf = e.meta.expected != null &&
          Object.prototype.hasOwnProperty.call(e.meta.expected, "valueOf");

        // Known diffs: test moment2 behavior independently (no oracle comparison)
        const isKnownDiff = e.meta.bugClass?.toLowerCase().includes("known-diff");

        if (isKnownDiff) {
          lines.push(`test("KNOWN DIFF: ${e.meta.bugClass}: ${e.name}", () => {`);
          lines.push(`  const input = ${input};`);
          lines.push("  const m2 = moment(input);");
          lines.push("  // Known diff — moment.js may differ. Verify moment2 is deterministic.");
          lines.push("  expect(typeof m2.isValid()).toBe('boolean');");
          lines.push("  if (m2.isValid()) {");
          lines.push("    expect(typeof m2.valueOf()).toBe('number');");
          lines.push("  }");
          lines.push("});");
          lines.push("");
        } else if (hasExpectedIsValid || hasExpectedValueOf) {
          // Specific expected behavior
          lines.push(`test(${desc}, () => {`);
          lines.push(`  const input = ${input};`);
          lines.push("  const m2 = moment(input);");
          lines.push("  const mo = originalMoment(input);");

          if (hasExpectedIsValid) {
            lines.push(`  expect(m2.isValid()).toBe(${e.meta.expected!.isValid});`);
            lines.push(`  expect(mo.isValid()).toBe(${e.meta.expected!.isValid});`);
          } else {
            lines.push("  expect(m2.isValid()).toBe(mo.isValid());");
          }

          if (hasExpectedValueOf) {
            lines.push(`  expect(m2.valueOf()).toBe(${e.meta.expected!.valueOf});`);
          } else {
            lines.push("  if (m2.isValid() && mo.isValid()) {");
            lines.push("    expect(m2.valueOf()).toBe(mo.valueOf());");
            lines.push("  }");
          }

          lines.push("});");
          lines.push("");
        } else {
          // Standard oracle comparison
          lines.push(`test(${desc}, () => {`);
          lines.push(`  const input = ${input};`);
          lines.push("  const m2 = moment(input);");
          lines.push("  const mo = originalMoment(input);");
          lines.push("  expect(m2.isValid()).toBe(mo.isValid());");
          lines.push("  if (m2.isValid() && mo.isValid()) {");
          lines.push("    expect(m2.valueOf()).toBe(mo.valueOf());");
          lines.push("  }");
          lines.push("});");
          lines.push("");
        }
      }
    }
  }

  return lines.join("\n");
}

function main(): void {
  console.log("Collecting regression entries...");
  const entries = collectEntries();
  console.log(`Found ${entries.length} entries`);

  const code = generateTestFile(entries);

  mkdirSync(resolve(ROOT, "test", "regression"), { recursive: true });
  writeFileSync(OUTPUT, code, "utf-8");
  console.log(`Generated ${OUTPUT}`);
  console.log(`  ${entries.length} test cases`);
}

main();
